# Changes here will be overwritten by Copier.
_commit: 1.11.0
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2023'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC
insiders: false
project_description: A development dashboard for your projects.
project_name: Devboard
python_package_command_line_name: devboard
python_package_distribution_name: devboard
python_package_import_name: devboard
repository_name: devboard
repository_namespace: pawamoy
repository_provider: github.com

